name: build-html-action
env:
  S3_BUCKET_NAME     : "git-action-codedeploy-deployments"
  CODE_DEPLOY_NAME   : "git-actions"
  DEV_GROUP_NAME     : "develop"
  DEPLOY_PACKAGE_NAME: "index.html"
  APPSPEC_NAME       : "appspec.yml"
  AWS_REGION_NAME    : "eu-central-1"

on: 
  push:
    branches:
      - main

jobs:
  test-ci-part:
    runs-on: ubuntu-latest
    
    steps:
    - name: GIT clone repo
      uses: actions/checkout@v1
    
    - name: Config AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region           : ${{ env.AWS_REGION_NAME }}
    
    - name: Copy Dep package to S3 bucket
      run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.S3_BUCKET_NAME }}/
      
    - name: Print OK message
      run : echo "All done"
      
  test-cd-part:
    runs-on: ubuntu-latest
    needs  : [test-ci-part]
    
    steps:   
    - name: GIT clone repo
      uses: actions/checkout@v1
    
    - name: pwd
      run : pwd
    
    - name: ls
      run : ls -la
      
    - name: AWS CodeDeploy
      uses: sourcetoad/aws-codedeploy-action@v1
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        aws_region: ${{ env.AWS_REGION_NAME }}
        codedeploy_name: ${{ env.CODE_DEPLOY_NAME }}
        codedeploy_group: ${{ env.DEV_GROUP_NAME }}
        s3_bucket: ${{ env.S3_BUCKET_NAME }}
        s3_folder: ${{ env.S3_BUCKET_NAME }}
        
        
