name: build-html-action
env:
  S3_BUCKET_NAME     : "git-action-codedeploy-deployments"
  CODE_DEPLOY_NAME   : "git-actions"
  DEV_GROUP_NAME     : "develop"
  DEPLOY_PACKAGE_NAME: "index.html"
  APPSPEC_NAME       : "appspec.yml"
  AWS_REGION_NAME    : "eu-central-1"

on: 
  push:
    branches:
      - main

jobs:
  test-ci-part:
    runs-on: ubuntu-latest
    
    steps:
    - name: GIT clone repo
      uses: actions/checkout@v1
    
    - name: Config AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region           : ${{ env.AWS_REGION_NAME }}
    
    - name: Copy Dep package to S3 bucket
      run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.S3_BUCKET_NAME }}/
      
    - name: Print OK message
      run : echo "All done"
      
  test-cd-part:
    runs-on: ubuntu-latest
    needs  : [test-ci-part]
    
    steps:   
    - name: GIT clone repo
      uses: actions/checkout@v1
    
    - name: pwd
      run : pwd
    
    - name: ls
      run : ls -la
      
    
    - name: Creating AWS Deployment
      run: |
          aws deploy create-deployment \
          --application-name ${{ env.CODE_DEPLOY_NAME }} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name ${{ env.DEV_GROUP_NAME }} \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=${{ env.S3_BUCKET_NAME }},key=${{ env.DEPLOY_PACKAGE_NAME }},bundleType=html \
