name: build-html-action-s3-code-deploy
env:
  S3_BUCKET_NAME     : "git-action-codedeploy-deployments"
  CODE_DEPLOY_NAME   : "git-actions"
  DEV_GROUP_NAME     : "develop"
  DEPLOY_PACKAGE_NAME: "index.html_${{ github.sha }}.zip"
  AWS_REGION_NAME    : "eu-central-1"

on: 
  push:
    branches:
      - main

jobs:    
  test-ci-cd-part:
    runs-on: ubuntu-latest
    
    steps:   
    - name: GIT clone repo CD
      uses: actions/checkout@v1
      
      
          
    - name: Config CD AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region           : ${{ env.AWS_REGION_NAME }}
        
    - name: aws deploy push
      run : |
          aws deploy push \
          --application-name ${{ env.CODE_DEPLOY_NAME }} \
          --description "This is a revision for the test" \
          --ignore-hidden-files \
          --s3-location s3://${{ env.S3_BUCKET_NAME }}/${{ env.DEPLOY_PACKAGE_NAME }}.zip \
          --source .
    
    - name: Creating AWS Deployment
      run : |
          aws deploy create-deployment \
          --application-name ${{ env.CODE_DEPLOY_NAME }} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name ${{ env.DEV_GROUP_NAME }} \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=${{ env.S3_BUCKET_NAME }},key=${{ env.DEPLOY_PACKAGE_NAME }}.zip,bundleType=zip \
